/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Comment model passed on insert to the database
 * @export
 * @interface CommentInsertModel
 */
export interface CommentInsertModel {
    /**
     * 
     * @type {any}
     * @memberof CommentInsertModel
     */
    placeId: any | null;
    /**
     * 
     * @type {any}
     * @memberof CommentInsertModel
     */
    text: any | null;
}

/**
 * Check if a given object implements the CommentInsertModel interface.
 */
export function instanceOfCommentInsertModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "placeId" in value;
    isInstance = isInstance && "text" in value;

    return isInstance;
}

export function CommentInsertModelFromJSON(json: any): CommentInsertModel {
    return CommentInsertModelFromJSONTyped(json, false);
}

export function CommentInsertModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentInsertModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'placeId': json['place_id'],
        'text': json['text'],
    };
}

export function CommentInsertModelToJSON(value?: CommentInsertModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'place_id': value.placeId,
        'text': value.text,
    };
}

