/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Comments
 */
export interface Comments {
}

/**
 * Check if a given object implements the Comments interface.
 */
export function instanceOfComments(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommentsFromJSON(json: any): Comments {
    return CommentsFromJSONTyped(json, false);
}

export function CommentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comments {
    return json;
}

export function CommentsToJSON(value?: Comments | null): any {
    return value;
}

