/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MinRating
 */
export interface MinRating {
}

/**
 * Check if a given object implements the MinRating interface.
 */
export function instanceOfMinRating(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MinRatingFromJSON(json: any): MinRating {
    return MinRatingFromJSONTyped(json, false);
}

export function MinRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinRating {
    return json;
}

export function MinRatingToJSON(value?: MinRating | null): any {
    return value;
}

