/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlusCode
 */
export interface PlusCode {
    /**
     * 
     * @type {string}
     * @memberof PlusCode
     */
    compoundCode: string;
    /**
     * 
     * @type {string}
     * @memberof PlusCode
     */
    globalCode: string;
}

/**
 * Check if a given object implements the PlusCode interface.
 */
export function instanceOfPlusCode(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "compoundCode" in value;
    isInstance = isInstance && "globalCode" in value;

    return isInstance;
}

export function PlusCodeFromJSON(json: any): PlusCode {
    return PlusCodeFromJSONTyped(json, false);
}

export function PlusCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlusCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'compoundCode': json['compound_code'],
        'globalCode': json['global_code'],
    };
}

export function PlusCodeToJSON(value?: PlusCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'compound_code': value.compoundCode,
        'global_code': value.globalCode,
    };
}

