/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceLevel
 */
export interface PriceLevel {
}

/**
 * Check if a given object implements the PriceLevel interface.
 */
export function instanceOfPriceLevel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PriceLevelFromJSON(json: any): PriceLevel {
    return PriceLevelFromJSONTyped(json, false);
}

export function PriceLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceLevel {
    return json;
}

export function PriceLevelToJSON(value?: PriceLevel | null): any {
    return value;
}

