/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReservationUrl
 */
export interface ReservationUrl {
}

/**
 * Check if a given object implements the ReservationUrl interface.
 */
export function instanceOfReservationUrl(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReservationUrlFromJSON(json: any): ReservationUrl {
    return ReservationUrlFromJSONTyped(json, false);
}

export function ReservationUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationUrl {
    return json;
}

export function ReservationUrlToJSON(value?: ReservationUrl | null): any {
    return value;
}

