/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
} from './Collection';
import type { Comments } from './Comments';
import {
    CommentsFromJSON,
    CommentsFromJSONTyped,
    CommentsToJSON,
} from './Comments';
import type { Geometry } from './Geometry';
import {
    GeometryFromJSON,
    GeometryFromJSONTyped,
    GeometryToJSON,
} from './Geometry';
import type { Id } from './Id';
import {
    IdFromJSON,
    IdFromJSONTyped,
    IdToJSON,
} from './Id';
import type { Place } from './Place';
import {
    PlaceFromJSON,
    PlaceFromJSONTyped,
    PlaceToJSON,
} from './Place';
import type { PlusCode } from './PlusCode';
import {
    PlusCodeFromJSON,
    PlusCodeFromJSONTyped,
    PlusCodeToJSON,
} from './PlusCode';
import type { PriceLevel } from './PriceLevel';
import {
    PriceLevelFromJSON,
    PriceLevelFromJSONTyped,
    PriceLevelToJSON,
} from './PriceLevel';
import type { Rating } from './Rating';
import {
    RatingFromJSON,
    RatingFromJSONTyped,
    RatingToJSON,
} from './Rating';
import type { ReservationUrl } from './ReservationUrl';
import {
    ReservationUrlFromJSON,
    ReservationUrlFromJSONTyped,
    ReservationUrlToJSON,
} from './ReservationUrl';

/**
 * 
 * @export
 * @interface ResponseGetOneGetNameGet
 */
export interface ResponseGetOneGetNameGet {
    /**
     * 
     * @type {Id}
     * @memberof ResponseGetOneGetNameGet
     */
    id?: Id;
    /**
     * 
     * @type {any}
     * @memberof ResponseGetOneGetNameGet
     */
    businessStatus: any | null;
    /**
     * 
     * @type {any}
     * @memberof ResponseGetOneGetNameGet
     */
    formattedAddress: any | null;
    /**
     * 
     * @type {Geometry}
     * @memberof ResponseGetOneGetNameGet
     */
    geometry: Geometry;
    /**
     * 
     * @type {any}
     * @memberof ResponseGetOneGetNameGet
     */
    iconBackgroundColor: any | null;
    /**
     * 
     * @type {any}
     * @memberof ResponseGetOneGetNameGet
     */
    iconMaskBaseUri: any | null;
    /**
     * 
     * @type {any}
     * @memberof ResponseGetOneGetNameGet
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof ResponseGetOneGetNameGet
     */
    placeId: any | null;
    /**
     * 
     * @type {PlusCode}
     * @memberof ResponseGetOneGetNameGet
     */
    plusCode: PlusCode;
    /**
     * 
     * @type {any}
     * @memberof ResponseGetOneGetNameGet
     */
    reference: any | null;
    /**
     * 
     * @type {any}
     * @memberof ResponseGetOneGetNameGet
     */
    types: any | null;
    /**
     * 
     * @type {any}
     * @memberof ResponseGetOneGetNameGet
     */
    userRatingsTotal: any | null;
    /**
     * 
     * @type {PriceLevel}
     * @memberof ResponseGetOneGetNameGet
     */
    priceLevel?: PriceLevel;
    /**
     * 
     * @type {Rating}
     * @memberof ResponseGetOneGetNameGet
     */
    rating?: Rating;
    /**
     * 
     * @type {Collection}
     * @memberof ResponseGetOneGetNameGet
     */
    collection?: Collection;
    /**
     * 
     * @type {ReservationUrl}
     * @memberof ResponseGetOneGetNameGet
     */
    reservationUrl?: ReservationUrl;
    /**
     * 
     * @type {Comments}
     * @memberof ResponseGetOneGetNameGet
     */
    comments?: Comments;
}

/**
 * Check if a given object implements the ResponseGetOneGetNameGet interface.
 */
export function instanceOfResponseGetOneGetNameGet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "businessStatus" in value;
    isInstance = isInstance && "formattedAddress" in value;
    isInstance = isInstance && "geometry" in value;
    isInstance = isInstance && "iconBackgroundColor" in value;
    isInstance = isInstance && "iconMaskBaseUri" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "placeId" in value;
    isInstance = isInstance && "plusCode" in value;
    isInstance = isInstance && "reference" in value;
    isInstance = isInstance && "types" in value;
    isInstance = isInstance && "userRatingsTotal" in value;

    return isInstance;
}

export function ResponseGetOneGetNameGetFromJSON(json: any): ResponseGetOneGetNameGet {
    return ResponseGetOneGetNameGetFromJSONTyped(json, false);
}

export function ResponseGetOneGetNameGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseGetOneGetNameGet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : IdFromJSON(json['id']),
        'businessStatus': json['business_status'],
        'formattedAddress': json['formatted_address'],
        'geometry': GeometryFromJSON(json['geometry']),
        'iconBackgroundColor': json['icon_background_color'],
        'iconMaskBaseUri': json['icon_mask_base_uri'],
        'name': json['name'],
        'placeId': json['place_id'],
        'plusCode': PlusCodeFromJSON(json['plus_code']),
        'reference': json['reference'],
        'types': json['types'],
        'userRatingsTotal': json['user_ratings_total'],
        'priceLevel': !exists(json, 'price_level') ? undefined : PriceLevelFromJSON(json['price_level']),
        'rating': !exists(json, 'rating') ? undefined : RatingFromJSON(json['rating']),
        'collection': !exists(json, 'collection') ? undefined : CollectionFromJSON(json['collection']),
        'reservationUrl': !exists(json, 'reservation_url') ? undefined : ReservationUrlFromJSON(json['reservation_url']),
        'comments': !exists(json, 'comments') ? undefined : CommentsFromJSON(json['comments']),
    };
}

export function ResponseGetOneGetNameGetToJSON(value?: ResponseGetOneGetNameGet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': IdToJSON(value.id),
        'business_status': value.businessStatus,
        'formatted_address': value.formattedAddress,
        'geometry': GeometryToJSON(value.geometry),
        'icon_background_color': value.iconBackgroundColor,
        'icon_mask_base_uri': value.iconMaskBaseUri,
        'name': value.name,
        'place_id': value.placeId,
        'plus_code': PlusCodeToJSON(value.plusCode),
        'reference': value.reference,
        'types': value.types,
        'user_ratings_total': value.userRatingsTotal,
        'price_level': PriceLevelToJSON(value.priceLevel),
        'rating': RatingToJSON(value.rating),
        'collection': CollectionToJSON(value.collection),
        'reservation_url': ReservationUrlToJSON(value.reservationUrl),
        'comments': CommentsToJSON(value.comments),
    };
}

