/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIKey,
  Address,
  CommentInsertModel,
  CommentModel,
  HTTPValidationError,
  MinRating,
  Name,
  Place,
  PlaceInsertModel,
  ResponseGetOneGetNameGet,
} from '../models/index';
import {
    APIKeyFromJSON,
    APIKeyToJSON,
    AddressFromJSON,
    AddressToJSON,
    CommentInsertModelFromJSON,
    CommentInsertModelToJSON,
    CommentModelFromJSON,
    CommentModelToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MinRatingFromJSON,
    MinRatingToJSON,
    NameFromJSON,
    NameToJSON,
    PlaceFromJSON,
    PlaceToJSON,
    PlaceInsertModelFromJSON,
    PlaceInsertModelToJSON,
    ResponseGetOneGetNameGetFromJSON,
    ResponseGetOneGetNameGetToJSON,
} from '../models/index';

export interface AddAddPostRequest {
    name: string;
    location: string;
}

export interface AddCommentCommentsAddPostRequest {
    commentInsertModel: CommentInsertModel;
}

export interface AddManyAddManyPostRequest {
    placeInsertModel: Array<PlaceInsertModel>;
}

export interface DeleteDeletePostRequest {
    placeId: string;
}

export interface DeleteManyDeleteManyPostRequest {
    requestBody: Array<string>;
}

export interface GetCommentsCommentsGetGetRequest {
    placeId: any;
}

export interface GetOneGetNameGetRequest {
    name: any;
    exact?: any;
}

export interface SearchSearchGetRequest {
    name?: Name;
    address?: Address;
    minRating?: MinRating;
    exact?: any;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Add a restaurant to the database.  Args:     name (str): Name of the restaurant     location (str): Address of the restaurant
     * Add
     */
    async addAddPostRaw(requestParameters: AddAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Place>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling addAddPost.');
        }

        if (requestParameters.location === null || requestParameters.location === undefined) {
            throw new runtime.RequiredError('location','Required parameter requestParameters.location was null or undefined when calling addAddPost.');
        }

        const queryParameters: any = {};

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.location !== undefined) {
            queryParameters['location'] = requestParameters.location;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaceFromJSON(jsonValue));
    }

    /**
     * Add a restaurant to the database.  Args:     name (str): Name of the restaurant     location (str): Address of the restaurant
     * Add
     */
    async addAddPost(requestParameters: AddAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Place> {
        const response = await this.addAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a restaurant to the database.  Args:     comment (Comment): Comment to add to the place
     * Add Comment
     */
    async addCommentCommentsAddPostRaw(requestParameters: AddCommentCommentsAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentModel>> {
        if (requestParameters.commentInsertModel === null || requestParameters.commentInsertModel === undefined) {
            throw new runtime.RequiredError('commentInsertModel','Required parameter requestParameters.commentInsertModel was null or undefined when calling addCommentCommentsAddPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/comments/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommentInsertModelToJSON(requestParameters.commentInsertModel),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentModelFromJSON(jsonValue));
    }

    /**
     * Add a restaurant to the database.  Args:     comment (Comment): Comment to add to the place
     * Add Comment
     */
    async addCommentCommentsAddPost(requestParameters: AddCommentCommentsAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentModel> {
        const response = await this.addCommentCommentsAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add multiple restaurants to the database.  Args:     places (List[Dict[str, str]]): List of restaurants to add
     * Add Many
     */
    async addManyAddManyPostRaw(requestParameters: AddManyAddManyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Place>>> {
        if (requestParameters.placeInsertModel === null || requestParameters.placeInsertModel === undefined) {
            throw new runtime.RequiredError('placeInsertModel','Required parameter requestParameters.placeInsertModel was null or undefined when calling addManyAddManyPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/add/many`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.placeInsertModel.map(PlaceInsertModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlaceFromJSON));
    }

    /**
     * Add multiple restaurants to the database.  Args:     places (List[Dict[str, str]]): List of restaurants to add
     * Add Many
     */
    async addManyAddManyPost(requestParameters: AddManyAddManyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Place>> {
        const response = await this.addManyAddManyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Simple, delete single place.
     * Delete
     */
    async deleteDeletePostRaw(requestParameters: DeleteDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.placeId === null || requestParameters.placeId === undefined) {
            throw new runtime.RequiredError('placeId','Required parameter requestParameters.placeId was null or undefined when calling deleteDeletePost.');
        }

        const queryParameters: any = {};

        if (requestParameters.placeId !== undefined) {
            queryParameters['place_id'] = requestParameters.placeId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Simple, delete single place.
     * Delete
     */
    async deleteDeletePost(requestParameters: DeleteDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Simple, delete multiple places.
     * Delete Many
     */
    async deleteManyDeleteManyPostRaw(requestParameters: DeleteManyDeleteManyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.requestBody === null || requestParameters.requestBody === undefined) {
            throw new runtime.RequiredError('requestBody','Required parameter requestParameters.requestBody was null or undefined when calling deleteManyDeleteManyPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/delete/many`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.requestBody,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Simple, delete multiple places.
     * Delete Many
     */
    async deleteManyDeleteManyPost(requestParameters: DeleteManyDeleteManyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteManyDeleteManyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all restaurants.
     * Get All
     */
    async getAllAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get all restaurants.
     * Get All
     */
    async getAllAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getAllAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get all comments for a place.  Args:     place_id (str): Place to get comments for
     * Get Comments
     */
    async getCommentsCommentsGetGetRaw(requestParameters: GetCommentsCommentsGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.placeId === null || requestParameters.placeId === undefined) {
            throw new runtime.RequiredError('placeId','Required parameter requestParameters.placeId was null or undefined when calling getCommentsCommentsGetGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.placeId !== undefined) {
            queryParameters['place_id'] = requestParameters.placeId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/comments/get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get all comments for a place.  Args:     place_id (str): Place to get comments for
     * Get Comments
     */
    async getCommentsCommentsGetGet(requestParameters: GetCommentsCommentsGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getCommentsCommentsGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the Google api key.
     * Get Google Api Key
     */
    async getGoogleApiKeyKeysGoogleGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIKey>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/keys/google`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIKeyFromJSON(jsonValue));
    }

    /**
     * Get the Google api key.
     * Get Google Api Key
     */
    async getGoogleApiKeyKeysGoogleGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIKey> {
        const response = await this.getGoogleApiKeyKeysGoogleGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get one restaurant by name  Args:     name (str): Name of the restaurant to get     exact (bool, optional): Exact match for name. Defaults to False.
     * Get One
     */
    async getOneGetNameGetRaw(requestParameters: GetOneGetNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseGetOneGetNameGet>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling getOneGetNameGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.exact !== undefined) {
            queryParameters['exact'] = requestParameters.exact;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/get/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseGetOneGetNameGetFromJSON(jsonValue));
    }

    /**
     * Get one restaurant by name  Args:     name (str): Name of the restaurant to get     exact (bool, optional): Exact match for name. Defaults to False.
     * Get One
     */
    async getOneGetNameGet(requestParameters: GetOneGetNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseGetOneGetNameGet> {
        const response = await this.getOneGetNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read Root
     */
    async readRootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Read Root
     */
    async readRootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.readRootGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search for a restaurant by name.  Args:     name (str, optional): Name of the restaurant to lookup. Defaults to None.     address (str, optional): Address of the restaurant to lookup. Defaults to None.     min_rating (float, optional): Minimum rating for the restaurant. Defaults to None.     exact (bool, optional): Exact match for name. Defaults to False.
     * Search
     */
    async searchSearchGetRaw(requestParameters: SearchSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.address !== undefined) {
            queryParameters['address'] = requestParameters.address;
        }

        if (requestParameters.minRating !== undefined) {
            queryParameters['min_rating'] = requestParameters.minRating;
        }

        if (requestParameters.exact !== undefined) {
            queryParameters['exact'] = requestParameters.exact;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Search for a restaurant by name.  Args:     name (str, optional): Name of the restaurant to lookup. Defaults to None.     address (str, optional): Address of the restaurant to lookup. Defaults to None.     min_rating (float, optional): Minimum rating for the restaurant. Defaults to None.     exact (bool, optional): Exact match for name. Defaults to False.
     * Search
     */
    async searchSearchGet(requestParameters: SearchSearchGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.searchSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
